@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.toblexson.alchematurgy.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;