@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.toblexson.alchematurgy.registry;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;